version: '3.8'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: node cli.js
